apiVersion: v1
kind: Template
metadata:
  name: backup-cronjobs
  annotations:
    description: "rsnapshot backup cronjobs"
parameters:
  - name: APP_NAME
    description: "App/deploymentconfig name"
    value: webanno
  - name: BACKUP_VOLUME
    description: "Backup volume to use"
    value: backup
  - name: DATA_VOLUME
    description: "Data volume to backup"
    value: webanno-files
  - name: RETAIN_HOURLY
    description: "How many hourly backups to retain"
    value: "24"
  - name: RETAIN_DAILY
    description: "How many daily backups to retain"
    value: "7"
  - name: RETAIN_WEEKLY
    description: "How many weekly backups to retain"
    value: "4"
  - name: RETAIN_MONTHLY
    description: "How many monthly backups to retain"
    value: "12"
  - name: RETAIN_YEARLY
    description: "How many yearly backups to retain"
    value: "3"
  - name: HOURLY_SCHEDULE
    description: 'Hourly cron schedule. Format "minute hour day month weekday"'
    value: "5 * * * *"
  - name: DAILY_SCHEDULE
    description: 'Daily cron schedule. Format "minute hour day month weekday"'
    value: "20 4 * * *"
  - name: WEEKLY_SCHEDULE
    description: 'Weekly cron schedule. Format "minute hour day month weekday"'
    value: "30 4 * * 0"
  - name: MONTHLY_SCHEDULE
    description: 'Monthly cron schedule. Format "minute hour day month weekday"'
    value: "40 4 1 * *"
  - name: YEARLY_SCHEDULE
    description: 'Yearly cron schedule. Format "minute hour day month weekday"'
    value: "50 4 1 1 *"
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APP_NAME}
        backup: ${APP_NAME}
      name: ${APP_NAME}-backup-hourly-cronjob
    spec:
      concurrencyPolicy: Forbid
      schedule: ${HOURLY_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                backup: ${APP_NAME}
                parent: ${APP_NAME}-backup-hourly
            spec:
              affinity:
                podAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: deploymentconfig
                            operator: In
                            values:
                              - ${APP_NAME}
                      topologyKey: kubernetes.io/hostname
              containers:
                - env:
                    - name: BACKUP_NAME
                      value: ${DATA_VOLUME}
                    - name: BACKUP_RETAIN
                      value: ${RETAIN_HOURLY}
                    - name: BACKUP_ROTATION
                      value: hourly
                  image: "docker.io/hsci/rsnapshot-openshift:latest"
                  imagePullPolicy: Always
                  name: rsnapshot
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                      readOnly: true
                    - mountPath: /backup/
                      name: backup
              restartPolicy: OnFailure
              volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: ${DATA_VOLUME}
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${BACKUP_VOLUME}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APP_NAME}
        backup: ${APP_NAME}
      name: ${APP_NAME}-backup-daily-cronjob
    spec:
      concurrencyPolicy: Forbid
      schedule: ${DAILY_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                backup: ${APP_NAME}
                parent: ${APP_NAME}-backup-daily
            spec:
              affinity:
                podAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: deploymentconfig
                            operator: In
                            values:
                              - ${APP_NAME}
                      topologyKey: kubernetes.io/hostname
              containers:
                - env:
                    - name: BACKUP_NAME
                      value: ${DATA_VOLUME}
                    - name: BACKUP_RETAIN
                      value: ${RETAIN_DAILY}
                    - name: BACKUP_ROTATION
                      value: daily
                  image: "docker.io/hsci/rsnapshot-openshift:latest"
                  imagePullPolicy: Always
                  name: rsnapshot
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                      readOnly: true
                    - mountPath: /backup/
                      name: backup
              restartPolicy: OnFailure
              volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: ${DATA_VOLUME}
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${BACKUP_VOLUME}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APP_NAME}
        backup: ${APP_NAME}
      name: ${APP_NAME}-backup-weekly-cronjob
    spec:
      concurrencyPolicy: Forbid
      schedule: ${WEEKLY_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                backup: ${APP_NAME}
                parent: ${APP_NAME}-backup-weekly
            spec:
              affinity:
                podAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: deploymentconfig
                            operator: In
                            values:
                              - ${APP_NAME}
                      topologyKey: kubernetes.io/hostname
              containers:
                - env:
                    - name: BACKUP_NAME
                      value: ${DATA_VOLUME}
                    - name: BACKUP_RETAIN
                      value: ${RETAIN_WEEKLY}
                    - name: BACKUP_ROTATION
                      value: weekly
                  image: "docker.io/hsci/rsnapshot-openshift:latest"
                  imagePullPolicy: Always
                  name: rsnapshot
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                      readOnly: true
                    - mountPath: /backup/
                      name: backup
              restartPolicy: OnFailure
              volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: ${DATA_VOLUME}
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${BACKUP_VOLUME}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APP_NAME}
        backup: ${APP_NAME}
      name: ${APP_NAME}-backup-monthly-cronjob
    spec:
      concurrencyPolicy: Forbid
      schedule: ${MONTHLY_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                backup: ${APP_NAME}
                parent: ${APP_NAME}-backup-monthly
            spec:
              affinity:
                podAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: deploymentconfig
                            operator: In
                            values:
                              - ${APP_NAME}
                      topologyKey: kubernetes.io/hostname
              containers:
                - env:
                    - name: BACKUP_NAME
                      value: ${DATA_VOLUME}
                    - name: BACKUP_RETAIN
                      value: ${RETAIN_MONTHLY}
                    - name: BACKUP_ROTATION
                      value: monthly
                  image: "docker.io/hsci/rsnapshot-openshift:latest"
                  imagePullPolicy: Always
                  name: rsnapshot
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                      readOnly: true
                    - mountPath: /backup/
                      name: backup
              restartPolicy: OnFailure
              volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: ${DATA_VOLUME}
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${BACKUP_VOLUME}
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: ${APP_NAME}
        backup: ${APP_NAME}
      name: ${APP_NAME}-backup-yearly-cronjob
    spec:
      concurrencyPolicy: Forbid
      schedule: ${YEARLY_SCHEDULE}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                backup: ${APP_NAME}
                parent: ${APP_NAME}-backup-yearly
            spec:
              affinity:
                podAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: deploymentconfig
                            operator: In
                            values:
                              - ${APP_NAME}
                      topologyKey: kubernetes.io/hostname
              containers:
                - env:
                    - name: BACKUP_NAME
                      value: ${DATA_VOLUME}
                    - name: BACKUP_RETAIN
                      value: ${RETAIN_YEARLY}
                    - name: BACKUP_ROTATION
                      value: monthly
                  image: "docker.io/hsci/rsnapshot-openshift:latest"
                  imagePullPolicy: Always
                  name: rsnapshot
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                      readOnly: true
                    - mountPath: /backup/
                      name: backup
              restartPolicy: OnFailure
              volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: ${DATA_VOLUME}
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${BACKUP_VOLUME}
